// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fuck.proto

package com.zing.netty.dto;

public final class Fuck {
    private Fuck() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface DemoMessage1OrBuilder extends
            // @@protoc_insertion_point(interface_extends:com.zing.netty.dto.DemoMessage1)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>string f1 = 1;</code>
         */
        java.lang.String getF1();

        /**
         * <code>string f1 = 1;</code>
         */
        com.google.protobuf.ByteString
        getF1Bytes();

        /**
         * <code>int32 f2 = 2;</code>
         */
        int getF2();

        /**
         * <code>bool f3 = 3;</code>
         */
        boolean getF3();
    }

    /**
     * Protobuf type {@code com.zing.netty.dto.DemoMessage1}
     */
    public static final class DemoMessage1 extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:com.zing.netty.dto.DemoMessage1)
            DemoMessage1OrBuilder {
        private static final long serialVersionUID = 0L;

        // Use DemoMessage1.newBuilder() to construct.
        private DemoMessage1(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private DemoMessage1() {
            f1_ = "";
            f2_ = 0;
            f3_ = false;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private DemoMessage1(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            java.lang.String s = input.readStringRequireUtf8();

                            f1_ = s;
                            break;
                        }
                        case 16: {

                            f2_ = input.readInt32();
                            break;
                        }
                        case 24: {

                            f3_ = input.readBool();
                            break;
                        }
                        default: {
                            if (!parseUnknownFieldProto3(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.zing.netty.dto.Fuck.internal_static_com_zing_netty_dto_DemoMessage1_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.zing.netty.dto.Fuck.internal_static_com_zing_netty_dto_DemoMessage1_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.zing.netty.dto.Fuck.DemoMessage1.class, com.zing.netty.dto.Fuck.DemoMessage1.Builder.class);
        }

        public static final int F1_FIELD_NUMBER = 1;
        private volatile java.lang.Object f1_;

        /**
         * <code>string f1 = 1;</code>
         */
        public java.lang.String getF1() {
            java.lang.Object ref = f1_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                f1_ = s;
                return s;
            }
        }

        /**
         * <code>string f1 = 1;</code>
         */
        public com.google.protobuf.ByteString
        getF1Bytes() {
            java.lang.Object ref = f1_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                f1_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int F2_FIELD_NUMBER = 2;
        private int f2_;

        /**
         * <code>int32 f2 = 2;</code>
         */
        public int getF2() {
            return f2_;
        }

        public static final int F3_FIELD_NUMBER = 3;
        private boolean f3_;

        /**
         * <code>bool f3 = 3;</code>
         */
        public boolean getF3() {
            return f3_;
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!getF1Bytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, f1_);
            }
            if (f2_ != 0) {
                output.writeInt32(2, f2_);
            }
            if (f3_ != false) {
                output.writeBool(3, f3_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!getF1Bytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, f1_);
            }
            if (f2_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(2, f2_);
            }
            if (f3_ != false) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBoolSize(3, f3_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.zing.netty.dto.Fuck.DemoMessage1)) {
                return super.equals(obj);
            }
            com.zing.netty.dto.Fuck.DemoMessage1 other = (com.zing.netty.dto.Fuck.DemoMessage1) obj;

            boolean result = true;
            result = result && getF1()
                    .equals(other.getF1());
            result = result && (getF2()
                    == other.getF2());
            result = result && (getF3()
                    == other.getF3());
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + F1_FIELD_NUMBER;
            hash = (53 * hash) + getF1().hashCode();
            hash = (37 * hash) + F2_FIELD_NUMBER;
            hash = (53 * hash) + getF2();
            hash = (37 * hash) + F3_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
                    getF3());
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static com.zing.netty.dto.Fuck.DemoMessage1 parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.zing.netty.dto.Fuck.DemoMessage1 parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.zing.netty.dto.Fuck.DemoMessage1 parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.zing.netty.dto.Fuck.DemoMessage1 parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.zing.netty.dto.Fuck.DemoMessage1 parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.zing.netty.dto.Fuck.DemoMessage1 parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.zing.netty.dto.Fuck.DemoMessage1 parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.zing.netty.dto.Fuck.DemoMessage1 parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.zing.netty.dto.Fuck.DemoMessage1 parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static com.zing.netty.dto.Fuck.DemoMessage1 parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.zing.netty.dto.Fuck.DemoMessage1 parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.zing.netty.dto.Fuck.DemoMessage1 parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(com.zing.netty.dto.Fuck.DemoMessage1 prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code com.zing.netty.dto.DemoMessage1}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:com.zing.netty.dto.DemoMessage1)
                com.zing.netty.dto.Fuck.DemoMessage1OrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.zing.netty.dto.Fuck.internal_static_com_zing_netty_dto_DemoMessage1_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.zing.netty.dto.Fuck.internal_static_com_zing_netty_dto_DemoMessage1_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                com.zing.netty.dto.Fuck.DemoMessage1.class, com.zing.netty.dto.Fuck.DemoMessage1.Builder.class);
            }

            // Construct using com.zing.netty.dto.Fuck.DemoMessage1.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                f1_ = "";

                f2_ = 0;

                f3_ = false;

                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.zing.netty.dto.Fuck.internal_static_com_zing_netty_dto_DemoMessage1_descriptor;
            }

            @java.lang.Override
            public com.zing.netty.dto.Fuck.DemoMessage1 getDefaultInstanceForType() {
                return com.zing.netty.dto.Fuck.DemoMessage1.getDefaultInstance();
            }

            @java.lang.Override
            public com.zing.netty.dto.Fuck.DemoMessage1 build() {
                com.zing.netty.dto.Fuck.DemoMessage1 result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public com.zing.netty.dto.Fuck.DemoMessage1 buildPartial() {
                com.zing.netty.dto.Fuck.DemoMessage1 result = new com.zing.netty.dto.Fuck.DemoMessage1(this);
                result.f1_ = f1_;
                result.f2_ = f2_;
                result.f3_ = f3_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return (Builder) super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.zing.netty.dto.Fuck.DemoMessage1) {
                    return mergeFrom((com.zing.netty.dto.Fuck.DemoMessage1) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.zing.netty.dto.Fuck.DemoMessage1 other) {
                if (other == com.zing.netty.dto.Fuck.DemoMessage1.getDefaultInstance()) return this;
                if (!other.getF1().isEmpty()) {
                    f1_ = other.f1_;
                    onChanged();
                }
                if (other.getF2() != 0) {
                    setF2(other.getF2());
                }
                if (other.getF3() != false) {
                    setF3(other.getF3());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.zing.netty.dto.Fuck.DemoMessage1 parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.zing.netty.dto.Fuck.DemoMessage1) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private java.lang.Object f1_ = "";

            /**
             * <code>string f1 = 1;</code>
             */
            public java.lang.String getF1() {
                java.lang.Object ref = f1_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    f1_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string f1 = 1;</code>
             */
            public com.google.protobuf.ByteString
            getF1Bytes() {
                java.lang.Object ref = f1_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    f1_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string f1 = 1;</code>
             */
            public Builder setF1(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                f1_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string f1 = 1;</code>
             */
            public Builder clearF1() {

                f1_ = getDefaultInstance().getF1();
                onChanged();
                return this;
            }

            /**
             * <code>string f1 = 1;</code>
             */
            public Builder setF1Bytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                f1_ = value;
                onChanged();
                return this;
            }

            private int f2_;

            /**
             * <code>int32 f2 = 2;</code>
             */
            public int getF2() {
                return f2_;
            }

            /**
             * <code>int32 f2 = 2;</code>
             */
            public Builder setF2(int value) {

                f2_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>int32 f2 = 2;</code>
             */
            public Builder clearF2() {

                f2_ = 0;
                onChanged();
                return this;
            }

            private boolean f3_;

            /**
             * <code>bool f3 = 3;</code>
             */
            public boolean getF3() {
                return f3_;
            }

            /**
             * <code>bool f3 = 3;</code>
             */
            public Builder setF3(boolean value) {

                f3_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>bool f3 = 3;</code>
             */
            public Builder clearF3() {

                f3_ = false;
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFieldsProto3(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:com.zing.netty.dto.DemoMessage1)
        }

        // @@protoc_insertion_point(class_scope:com.zing.netty.dto.DemoMessage1)
        private static final com.zing.netty.dto.Fuck.DemoMessage1 DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new com.zing.netty.dto.Fuck.DemoMessage1();
        }

        public static com.zing.netty.dto.Fuck.DemoMessage1 getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<DemoMessage1>
                PARSER = new com.google.protobuf.AbstractParser<DemoMessage1>() {
            @java.lang.Override
            public DemoMessage1 parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new DemoMessage1(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<DemoMessage1> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<DemoMessage1> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public com.zing.netty.dto.Fuck.DemoMessage1 getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface FuckMessageOrBuilder extends
            // @@protoc_insertion_point(interface_extends:com.zing.netty.dto.FuckMessage)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>map&lt;string, string&gt; message = 1;</code>
         */
        int getMessageCount();

        /**
         * <code>map&lt;string, string&gt; message = 1;</code>
         */
        boolean containsMessage(
                java.lang.String key);

        /**
         * Use {@link #getMessageMap()} instead.
         */
        @java.lang.Deprecated
        java.util.Map<java.lang.String, java.lang.String>
        getMessage();

        /**
         * <code>map&lt;string, string&gt; message = 1;</code>
         */
        java.util.Map<java.lang.String, java.lang.String>
        getMessageMap();

        /**
         * <code>map&lt;string, string&gt; message = 1;</code>
         */

        java.lang.String getMessageOrDefault(
                java.lang.String key,
                java.lang.String defaultValue);

        /**
         * <code>map&lt;string, string&gt; message = 1;</code>
         */

        java.lang.String getMessageOrThrow(
                java.lang.String key);
    }

    /**
     * Protobuf type {@code com.zing.netty.dto.FuckMessage}
     */
    public static final class FuckMessage extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:com.zing.netty.dto.FuckMessage)
            FuckMessageOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use FuckMessage.newBuilder() to construct.
        private FuckMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private FuckMessage() {
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private FuckMessage(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                                message_ = com.google.protobuf.MapField.newMapField(
                                        MessageDefaultEntryHolder.defaultEntry);
                                mutable_bitField0_ |= 0x00000001;
                            }
                            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
                                    message__ = input.readMessage(
                                    MessageDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                            message_.getMutableMap().put(
                                    message__.getKey(), message__.getValue());
                            break;
                        }
                        default: {
                            if (!parseUnknownFieldProto3(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.zing.netty.dto.Fuck.internal_static_com_zing_netty_dto_FuckMessage_descriptor;
        }

        @SuppressWarnings({"rawtypes"})
        @java.lang.Override
        protected com.google.protobuf.MapField internalGetMapField(
                int number) {
            switch (number) {
                case 1:
                    return internalGetMessage();
                default:
                    throw new RuntimeException(
                            "Invalid map field number: " + number);
            }
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.zing.netty.dto.Fuck.internal_static_com_zing_netty_dto_FuckMessage_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.zing.netty.dto.Fuck.FuckMessage.class, com.zing.netty.dto.Fuck.FuckMessage.Builder.class);
        }

        public static final int MESSAGE_FIELD_NUMBER = 1;

        private static final class MessageDefaultEntryHolder {
            static final com.google.protobuf.MapEntry<
                    java.lang.String, java.lang.String> defaultEntry =
                    com.google.protobuf.MapEntry
                            .<java.lang.String, java.lang.String>newDefaultInstance(
                                    com.zing.netty.dto.Fuck.internal_static_com_zing_netty_dto_FuckMessage_MessageEntry_descriptor,
                                    com.google.protobuf.WireFormat.FieldType.STRING,
                                    "",
                                    com.google.protobuf.WireFormat.FieldType.STRING,
                                    "");
        }

        private com.google.protobuf.MapField<
                java.lang.String, java.lang.String> message_;

        private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetMessage() {
            if (message_ == null) {
                return com.google.protobuf.MapField.emptyMapField(
                        MessageDefaultEntryHolder.defaultEntry);
            }
            return message_;
        }

        public int getMessageCount() {
            return internalGetMessage().getMap().size();
        }

        /**
         * <code>map&lt;string, string&gt; message = 1;</code>
         */

        public boolean containsMessage(
                java.lang.String key) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            return internalGetMessage().getMap().containsKey(key);
        }

        /**
         * Use {@link #getMessageMap()} instead.
         */
        @java.lang.Deprecated
        public java.util.Map<java.lang.String, java.lang.String> getMessage() {
            return getMessageMap();
        }

        /**
         * <code>map&lt;string, string&gt; message = 1;</code>
         */

        public java.util.Map<java.lang.String, java.lang.String> getMessageMap() {
            return internalGetMessage().getMap();
        }

        /**
         * <code>map&lt;string, string&gt; message = 1;</code>
         */

        public java.lang.String getMessageOrDefault(
                java.lang.String key,
                java.lang.String defaultValue) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            java.util.Map<java.lang.String, java.lang.String> map =
                    internalGetMessage().getMap();
            return map.containsKey(key) ? map.get(key) : defaultValue;
        }

        /**
         * <code>map&lt;string, string&gt; message = 1;</code>
         */

        public java.lang.String getMessageOrThrow(
                java.lang.String key) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            java.util.Map<java.lang.String, java.lang.String> map =
                    internalGetMessage().getMap();
            if (!map.containsKey(key)) {
                throw new java.lang.IllegalArgumentException();
            }
            return map.get(key);
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            com.google.protobuf.GeneratedMessageV3
                    .serializeStringMapTo(
                            output,
                            internalGetMessage(),
                            MessageDefaultEntryHolder.defaultEntry,
                            1);
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
                    : internalGetMessage().getMap().entrySet()) {
                com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
                        message__ = MessageDefaultEntryHolder.defaultEntry.newBuilderForType()
                        .setKey(entry.getKey())
                        .setValue(entry.getValue())
                        .build();
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(1, message__);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.zing.netty.dto.Fuck.FuckMessage)) {
                return super.equals(obj);
            }
            com.zing.netty.dto.Fuck.FuckMessage other = (com.zing.netty.dto.Fuck.FuckMessage) obj;

            boolean result = true;
            result = result && internalGetMessage().equals(
                    other.internalGetMessage());
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (!internalGetMessage().getMap().isEmpty()) {
                hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
                hash = (53 * hash) + internalGetMessage().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static com.zing.netty.dto.Fuck.FuckMessage parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.zing.netty.dto.Fuck.FuckMessage parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.zing.netty.dto.Fuck.FuckMessage parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.zing.netty.dto.Fuck.FuckMessage parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.zing.netty.dto.Fuck.FuckMessage parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.zing.netty.dto.Fuck.FuckMessage parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.zing.netty.dto.Fuck.FuckMessage parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.zing.netty.dto.Fuck.FuckMessage parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.zing.netty.dto.Fuck.FuckMessage parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static com.zing.netty.dto.Fuck.FuckMessage parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.zing.netty.dto.Fuck.FuckMessage parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.zing.netty.dto.Fuck.FuckMessage parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(com.zing.netty.dto.Fuck.FuckMessage prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code com.zing.netty.dto.FuckMessage}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:com.zing.netty.dto.FuckMessage)
                com.zing.netty.dto.Fuck.FuckMessageOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.zing.netty.dto.Fuck.internal_static_com_zing_netty_dto_FuckMessage_descriptor;
            }

            @SuppressWarnings({"rawtypes"})
            protected com.google.protobuf.MapField internalGetMapField(
                    int number) {
                switch (number) {
                    case 1:
                        return internalGetMessage();
                    default:
                        throw new RuntimeException(
                                "Invalid map field number: " + number);
                }
            }

            @SuppressWarnings({"rawtypes"})
            protected com.google.protobuf.MapField internalGetMutableMapField(
                    int number) {
                switch (number) {
                    case 1:
                        return internalGetMutableMessage();
                    default:
                        throw new RuntimeException(
                                "Invalid map field number: " + number);
                }
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.zing.netty.dto.Fuck.internal_static_com_zing_netty_dto_FuckMessage_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                com.zing.netty.dto.Fuck.FuckMessage.class, com.zing.netty.dto.Fuck.FuckMessage.Builder.class);
            }

            // Construct using com.zing.netty.dto.Fuck.FuckMessage.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                internalGetMutableMessage().clear();
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.zing.netty.dto.Fuck.internal_static_com_zing_netty_dto_FuckMessage_descriptor;
            }

            @java.lang.Override
            public com.zing.netty.dto.Fuck.FuckMessage getDefaultInstanceForType() {
                return com.zing.netty.dto.Fuck.FuckMessage.getDefaultInstance();
            }

            @java.lang.Override
            public com.zing.netty.dto.Fuck.FuckMessage build() {
                com.zing.netty.dto.Fuck.FuckMessage result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public com.zing.netty.dto.Fuck.FuckMessage buildPartial() {
                com.zing.netty.dto.Fuck.FuckMessage result = new com.zing.netty.dto.Fuck.FuckMessage(this);
                int from_bitField0_ = bitField0_;
                result.message_ = internalGetMessage();
                result.message_.makeImmutable();
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return (Builder) super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.zing.netty.dto.Fuck.FuckMessage) {
                    return mergeFrom((com.zing.netty.dto.Fuck.FuckMessage) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.zing.netty.dto.Fuck.FuckMessage other) {
                if (other == com.zing.netty.dto.Fuck.FuckMessage.getDefaultInstance()) return this;
                internalGetMutableMessage().mergeFrom(
                        other.internalGetMessage());
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.zing.netty.dto.Fuck.FuckMessage parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.zing.netty.dto.Fuck.FuckMessage) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private com.google.protobuf.MapField<
                    java.lang.String, java.lang.String> message_;

            private com.google.protobuf.MapField<java.lang.String, java.lang.String>
            internalGetMessage() {
                if (message_ == null) {
                    return com.google.protobuf.MapField.emptyMapField(
                            MessageDefaultEntryHolder.defaultEntry);
                }
                return message_;
            }

            private com.google.protobuf.MapField<java.lang.String, java.lang.String>
            internalGetMutableMessage() {
                onChanged();
                ;
                if (message_ == null) {
                    message_ = com.google.protobuf.MapField.newMapField(
                            MessageDefaultEntryHolder.defaultEntry);
                }
                if (!message_.isMutable()) {
                    message_ = message_.copy();
                }
                return message_;
            }

            public int getMessageCount() {
                return internalGetMessage().getMap().size();
            }

            /**
             * <code>map&lt;string, string&gt; message = 1;</code>
             */

            public boolean containsMessage(
                    java.lang.String key) {
                if (key == null) {
                    throw new java.lang.NullPointerException();
                }
                return internalGetMessage().getMap().containsKey(key);
            }

            /**
             * Use {@link #getMessageMap()} instead.
             */
            @java.lang.Deprecated
            public java.util.Map<java.lang.String, java.lang.String> getMessage() {
                return getMessageMap();
            }

            /**
             * <code>map&lt;string, string&gt; message = 1;</code>
             */

            public java.util.Map<java.lang.String, java.lang.String> getMessageMap() {
                return internalGetMessage().getMap();
            }

            /**
             * <code>map&lt;string, string&gt; message = 1;</code>
             */

            public java.lang.String getMessageOrDefault(
                    java.lang.String key,
                    java.lang.String defaultValue) {
                if (key == null) {
                    throw new java.lang.NullPointerException();
                }
                java.util.Map<java.lang.String, java.lang.String> map =
                        internalGetMessage().getMap();
                return map.containsKey(key) ? map.get(key) : defaultValue;
            }

            /**
             * <code>map&lt;string, string&gt; message = 1;</code>
             */

            public java.lang.String getMessageOrThrow(
                    java.lang.String key) {
                if (key == null) {
                    throw new java.lang.NullPointerException();
                }
                java.util.Map<java.lang.String, java.lang.String> map =
                        internalGetMessage().getMap();
                if (!map.containsKey(key)) {
                    throw new java.lang.IllegalArgumentException();
                }
                return map.get(key);
            }

            public Builder clearMessage() {
                internalGetMutableMessage().getMutableMap()
                        .clear();
                return this;
            }

            /**
             * <code>map&lt;string, string&gt; message = 1;</code>
             */

            public Builder removeMessage(
                    java.lang.String key) {
                if (key == null) {
                    throw new java.lang.NullPointerException();
                }
                internalGetMutableMessage().getMutableMap()
                        .remove(key);
                return this;
            }

            /**
             * Use alternate mutation accessors instead.
             */
            @java.lang.Deprecated
            public java.util.Map<java.lang.String, java.lang.String>
            getMutableMessage() {
                return internalGetMutableMessage().getMutableMap();
            }

            /**
             * <code>map&lt;string, string&gt; message = 1;</code>
             */
            public Builder putMessage(
                    java.lang.String key,
                    java.lang.String value) {
                if (key == null) {
                    throw new java.lang.NullPointerException();
                }
                if (value == null) {
                    throw new java.lang.NullPointerException();
                }
                internalGetMutableMessage().getMutableMap()
                        .put(key, value);
                return this;
            }

            /**
             * <code>map&lt;string, string&gt; message = 1;</code>
             */

            public Builder putAllMessage(
                    java.util.Map<java.lang.String, java.lang.String> values) {
                internalGetMutableMessage().getMutableMap()
                        .putAll(values);
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFieldsProto3(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:com.zing.netty.dto.FuckMessage)
        }

        // @@protoc_insertion_point(class_scope:com.zing.netty.dto.FuckMessage)
        private static final com.zing.netty.dto.Fuck.FuckMessage DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new com.zing.netty.dto.Fuck.FuckMessage();
        }

        public static com.zing.netty.dto.Fuck.FuckMessage getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<FuckMessage>
                PARSER = new com.google.protobuf.AbstractParser<FuckMessage>() {
            @java.lang.Override
            public FuckMessage parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new FuckMessage(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<FuckMessage> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<FuckMessage> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public com.zing.netty.dto.Fuck.FuckMessage getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_com_zing_netty_dto_DemoMessage1_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_com_zing_netty_dto_DemoMessage1_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_com_zing_netty_dto_FuckMessage_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_com_zing_netty_dto_FuckMessage_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_com_zing_netty_dto_FuckMessage_MessageEntry_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_com_zing_netty_dto_FuckMessage_MessageEntry_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\nfuck.proto\022\022com.zing.netty.dto\"2\n\014Demo" +
                        "Message1\022\n\n\002f1\030\001 \001(\t\022\n\n\002f2\030\002 \001(\005\022\n\n\002f3\030\003" +
                        " \001(\010\"|\n\013FuckMessage\022=\n\007message\030\001 \003(\0132,.c" +
                        "om.zing.netty.dto.FuckMessage.MessageEnt" +
                        "ry\032.\n\014MessageEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value" +
                        "\030\002 \001(\t:\0028\001b\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_com_zing_netty_dto_DemoMessage1_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_com_zing_netty_dto_DemoMessage1_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_com_zing_netty_dto_DemoMessage1_descriptor,
                new java.lang.String[]{"F1", "F2", "F3",});
        internal_static_com_zing_netty_dto_FuckMessage_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_com_zing_netty_dto_FuckMessage_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_com_zing_netty_dto_FuckMessage_descriptor,
                new java.lang.String[]{"Message",});
        internal_static_com_zing_netty_dto_FuckMessage_MessageEntry_descriptor =
                internal_static_com_zing_netty_dto_FuckMessage_descriptor.getNestedTypes().get(0);
        internal_static_com_zing_netty_dto_FuckMessage_MessageEntry_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_com_zing_netty_dto_FuckMessage_MessageEntry_descriptor,
                new java.lang.String[]{"Key", "Value",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
